### ISSUE TITLE
adding functions to user.c (FOR Utsav_Blaze)

### ISSUE THREAD

**Issue by NeoAnoman** [NeoAnoman/Let-s_Make_a_PROJECT#1]
# This project is for Utsav_Blaze  
In user.c file (you can find in main_project) 2 functions are needed.  
Below are provided the description of the function  
1st a file is needed on which these 2 functions work. File should be in binary format. filename='user.bin'  
# newuser()  
In this function you open the file user.bin FOR APPENDING iT. The information of new users are taken as input in a structure USER.  
DEFINING USER:
1st element id (int)  
2nd element Name (char string)  
3rd element Password (char string)  
YOU TAKE ONLY username and password as input from stdin  
Assigning ID:  
check the last structure in file and get the last id of user from here  
The new user id is (last id +1)
Now after input and id assignation store the whole structure into the file.
once the file is written successfully give the id to the user to store it with them  
# user()  
This function has 2 important things 1st login a user 2nd remove a user  
LOGIN:  
1st take input in stdin from user   
input contains username and password and the unique id that is given at the time of user creation  
search the matching id and check username and password  
If the credentials provided are correct then just call the function tm() with arguement of tm be the user structure that is accessed  
If credentials not correct then go to the begining of this method  
REMOVE:  
In this method of function 1st take the user id from stdin from user then ask them to enter username and password  
check credentials if are correct  
then display a confirmation to confirm if the user really wants to delete the account  
if no then go to INITIAL OF THE WHOLE FUNCTION and ask for login or remove  
if yes then delete the record and GO TO INITIAL  
IF the credentials not correct then just GO TO the begining of REMOVE method  
<br>
(if any doubts then contact me).

**Comment by NeoAnoman** [comment]
Please respond or report the status of project ASAP @utsav-blaze

**Comment by utsav-blaze** [comment]
I have completed my work and sent the PR so check it and ,merge to the main branch.

**Comment by NeoAnoman** [comment]
The issue will be closed for now If something shows up u will again be contacted,,,
