### ISSUE TITLE
The stat work in stat.c (FOR Dev Agarwal)

### ISSUE THREAD

**Issue by NeoAnoman** [NeoAnoman/Let-s_Make_a_PROJECT#2]
# This project is for Mr Dev Agarwal F1 batch  
You need to complete 3 definations of functions chstat , rmstat and statcmp  
A binary file known as stat.bin should be used in the project  
you have to maintain this file inyour project  
the file must contain all information stored in  a structure stat  
STAT DEFINING IS DONE IN PROJECT README
# chstat()  
has 1 arguement of user structure
This function is used to display all the stats of the provided user passed in the function  
compare the id of user 1st then display all the stats corresponding top that id in the file  
# rmstat()  
has 1 arguement of user structure
deletes the content corresponding to user id of file stat.bin and places 0 for every score  
of the user in all the challenges modes  
# statcmp()
has 2 arguements of  
user structure 
and stat structure(the stats needed to be compared)  
it compares the old stats with the new one passed and then replaces those which are better  
<br>
(for any doubts contact me)

**Comment by DarkStarp** [comment]
data file handling ke through store krani h information file mein ya kuch  aur way h ?

**Comment by NeoAnoman** [comment]
Do it with file handling only because we have to store the information permanently for later use...

**Comment by NeoAnoman** [comment]
Report the condition of the project ASAP @DarkStarp

**Comment by DarkStarp** [comment]
check the reset function of then user

**Comment by NeoAnoman** [comment]
The issue is solved for now If something shows up I will reopen this and u will be contacted again.
