### ISSUE TITLE
The word game challenge (for Krishare)

### ISSUE THREAD

**Issue by NeoAnoman** [NeoAnoman/Let-s_Make_a_PROJECT#5]
# This work is only for Krishare  
here you have to make a function in file challenges.c  
the function u have to make is  
# wgame(struct user u)   
u have to maintain a file with some words written in it  
Extract random words from that file  
display those random words on stdout  
now user have to type that word and as soon as he completely types the word check whether he typed correctly or not  
If correct than add score  
if not then decrease 1 life  
initialise the game with 5 lives per play  
maintain the score in the stat structure wscore and fscore,tscore must be 0 there  
at end of game (when all lives are over) pass stat to statcmp(u,stat)  
# Time System:-  
time is based on lvl  
lvl 1 : 6sec  
lvl 2 : 5.5sec  
decrease .5sec for every correct response till u get to 1.5 sec  
then time is fixed  
for every incorrect response increase time with 0.5 sec  
# Scoring system:-  
for lvl 1 5pts added for correct response  
now with increase in lvl u have to increase the points per correct response by 5  
so for lvl 2 the point for correct response is 10 and so on  
for any confusion or queries feel free to contact me.

**Comment by NeoAnoman** [comment]
The work for Krishare

**Comment by Krishare** [comment]
Check the pull request I have created related to my work

**Comment by NeoAnoman** [comment]
Yes I have checked your code It will be shortly merged I will tell you If any problem encountered

**Comment by NeoAnoman** [comment]
Will mark the issue completed once completely checked your work.

**Comment by NeoAnoman** [comment]
I checked your program and it seems its still incomplete there is a function rules() whose definations is missing.  
so complete all the functions and again give a pull request when completed.

**Comment by NeoAnoman** [comment]
I encountered a problem in the code probably because of exit() function.  
This function is exiting all the loops that are called before, resulting in end of the program.
Which is NOT NEEDED in the code so check if I am right and if yes then REPLACE ALL EXIT FUNCTIONS WITH BREAK STATEMENT.

**Comment by NeoAnoman** [comment]
The issue is solved and so the code has no problems with it leave the rest to me now. If u wanna add something more than inform me.
